### ISSUE TITLE
Goal enunciate:docs doesn't use dependency from reactor build

### ISSUE THREAD

**Issue by sparsick** [stoicflame/enunciate#1012]
Assume I have a multi-module Maven project with following structure:
```
project
|-module-a
|-module-b
```
module-a uses classes from module-b. When I change a class in module-b that is use in module-a, then the maven goal `mvn install enunciate:docs` fails with

```
[INFO] [ENUNCIATE] Using enunciate configuration at /home/jenkins/jenkins/workspace/example/enunciate.xml
[INFO] [ENUNCIATE] Enabled modules: [docs, jackson, jaxb, jaxrs, spring-web]
[WARNING] [ENUNCIATE] No documentation generated: there are no data types, services, or resources to document.
[WARNING] [ENUNCIATE] [javac] [ERROR] com.webcohesion.enunciate.Enunciate$URLFileObject[file:/home/jenkins/jenkins/workspace/example/module-a/src/main/java/com/example/module/Sample.java]:14:46 /home/jenkins/jenkins/workspace/example/module-a/src/main/java/com/example/module/Sample.java:14: error: package com.example.moduleb.SampleB does not exist
[WARNING] [ENUNCIATE] [javac] /home/jenkins/jenkins/workspace/example/module-a/src/main/java/com/example/module/Sample.java:14: error: package com.example.moduleb.SampleB does not exist
[WARNING] [ENUNCIATE] [javac] import com.example.moduleb.SampleB.CpRoleAssignment;
[WARNING] [ENUNCIATE] [javac]                                              ^
[WARNING] [ENUNCIATE] [javac] [ERROR] com.webcohesion.enunciate.Enunciate$URLFileObject[file:/home/jenkins/jenkins/workspace/example/module-a/src/main/java/com/example/module/Sample.java]:57:24 /home/jenkins/jenkins/workspace/example/module-a/src/main/java/com/example/module/Sample.java:57: error: cannot find symbol
[WARNING] [ENUNCIATE] [javac] /home/jenkins/jenkins/workspace/example/module-a/src/main/java/com/example/module/Sample.java:57: error: cannot find symbol
[WARNING] [ENUNCIATE] [javac]     public static List<SampleB> method(String a) {
[WARNING] [ENUNCIATE] [javac]                        ^
[WARNING] [ENUNCIATE] [javac]   symbol:   class SampleB
[WARNING] [ENUNCIATE] [javac]   location: class com.example.module.Sample
```
**Enunciate configuration**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.12.0.xsd">
    <modules>
        <swagger disabled="true"/>
        <jackson1 disabled="true"/>
        <jaxws disabled="true"/>
        <c-xml-client disabled="true"/>
        <csharp-xml-client disabled="true"/>
        <java-xml-client disabled="true"/>
        <java-json-client disabled="true"/>
        <javascript-client disabled="true"/>
        <gwt-json-client disabled="true"/>
        <gwt-json-overlay disabled="true"/>
        <obj-c-xml-client disabled="true"/>
        <php-xml-client disabled="true"/>
        <php-json-client disabled="true"/>
        <ruby-json-client disabled="true"/>
        <idl disabled="true"/>
    </modules>
</enunciate>

```

**Workaround**: I have to deploy my maven artifacts to the remote maven repository then I can run `mvn enunciate:docs` locally without failure

**Expected behavior:** Enunciate Maven Plugin uses maven artifacts from local maven repository for doc generation

**Comment by stoicflame** [comment]
I'm afraid I'm going to need some more detail because I can't reproduce the error.

An initial glace at the error message seems to imply that the problem might be with the sources jar that gets published with module-b. Can you please confirm that the `sources` plugin runs when you run `mvn install`?

When you say it fails with `enunciate:docs` does it work with the `enunciate:assemble` goal?

Can you put together a simple sample project that exposes the problem?

**Comment by sparsick** [comment]
Thanks @stoicflame for the hint with the `sources` plugin. This solves our problem. 

Another point:
In my team, we had the discussion that actually a `mvn generate-sources enunciate:docs` should be enough for the doc generation, because every information is available during the reactor build. Unfortunately, I need the jars in my local repo for running the goal `enunciate:docs` successfully.

**Comment by stoicflame** [comment]
> In my team, we had the discussion that actually a mvn compile enunciate:docs should be enough for the doc generation, because every information is available during the reactor build. Unfortunately, I need the jars in my local repo for running the goal enunciate:docs successfully.

Isn't that an issue with how Maven works? If "module-a uses classes from module-b" then `mvn compile` (no Enunciate) should fail too, yes? So unless I'm missing something I'd suggest taking your enhancement request to the Maven folks for consideration.

**Comment by sparsick** [comment]
> Isn't that an issue with how Maven works? If "module-a uses classes from module-b" then mvn compile (no Enunciate) should fail too, yes?

No, it isn't an issue with Maven. `mvn compile` works perfectly with "module-a uses classes from module-b".

**Comment by stoicflame** [comment]
Okay, I spent some here, but I can't currently figure out the issue as it currently stands.

The _title_ of the issues says that Enunciate doesn't use reactor dependencies, but I've been able to verify that Enunciate _does_ use reactor dependencies. I was able to prove that by running `mvn compile` on the [Enunciate sample app](https://github.com/stoicflame/enunciate-sample) (which has been refactored as a multi-module project), and everything works fine. So if that's the issue, I'd have to resolve it as "cannot reproduce."

The _description_ of the report includes an error saying that a `mvn install enunciate:docs` command fails with some compile error, but I can't reproduce that problem. Part of the reason I can't reproduce the problem is because I can't determine the expected behavior. A run of that command at the root of the [Enunciate sample app](https://github.com/stoicflame/enunciate-sample) says it can't find the `enunciate:docs` plugin, which is correct because the plugin is only configured in the `webapp` module. Running that command in the `webapp` module fails because it can't resolve the dependencies because they're not in the reactor build. So if that's the issue, I'd have to resolve it as "works as designed" or "cannot reproduce."

The _comments_ of the issue indicate a desire to have Enunciate look up the sources of the reactor project and include them in the build. But unfortunately, Maven doesn't provide the Enunciate plugin with any way to get those sources out of the reactor. So if that's the issue, I'd have to resolve it as "can't fix."

So any way I look at it, the issue seems closed to me. I'm happy to reopen as needed.
