### ISSUE TITLE
Unable to make basePath attribute of swagger configurable

### ISSUE THREAD

**Issue by SushmitaGoswami** [stoicflame/enunciate#1078]
I need to deploy a spring-boot application using an embedded and in a standalone tomcat.
So when I use the following configuration, swagger is working fine for embedded tomcat deployment since it has no application context.
`<swagger disabled="false" basePath="/api"/>`

However, when I try to deploy it using a standalone tomcat, it fails as the context path is getting appended.
e.g. http://localhost:8080/context_path/api/..., 
In this scenario, I received 404 when calling an api as it is pointing to **http://localhost:8080/api/** instead of **http://localhost:8080/context_path/api/**. 

So, how can I solve this issue? If I hard-code in basePath, then it will fail for embedded tomcat scenario.
Is there any other alternative to find solution to this issue? Can I make basePath configurable? Or Can I ask the enunciate plugin to include the application-context as well?

**Comment by stoicflame** [comment]
I'm afraid I don't have an easy solution for you because Enunciate generates static documentation. I'm open to suggestions and/or feature requests you might have.

Here are a couple of suggestions for paths you can pursue under the current limitations:

* Configure the standalone tomcat instance to remove the context path.
* Run Enunciate twice to generate two different sets of documentation.
* Do some kind of post-processing on the static Enunciate artifacts (e.g. `swagger.json`)

**Comment by SushmitaGoswami** [comment]
Sure. I am raising a feature request.
