### ISSUE TITLE
Special solutions are required to run Enunciate on JDK 16+

### ISSUE THREAD

**Issue by stevenschlansker** [stoicflame/enunciate#1087]
Upgraded to jdk 16 this morning and I noticed that enunciate seems to be incompatible:

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.13.3:docs (default) on project service-api-docs: Execution default of goal com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.13.3:docs failed: An API incompatibility was encountered while executing com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.13.3:docs: java.lang.IllegalAccessError: class com.webcohesion.enunciate.Enunciate (in unnamed module @0x26fe23e7) cannot access class com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x26fe23e7

Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.13.3:docs: java.lang.IllegalAccessError: class com.webcohesion.enunciate.Enunciate (in unnamed module @0x26fe23e7) cannot access class com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x26fe23e7
-----------------------------------------------------
Caused by: java.lang.IllegalAccessError: class com.webcohesion.enunciate.Enunciate (in unnamed module @0x26fe23e7) cannot access class com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x26fe23e7
    at com.webcohesion.enunciate.Enunciate.run (Enunciate.java:687)
    at com.webcohesion.enunciate.mojo.ConfigMojo.execute (ConfigMojo.java:436)
    at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute (DocsBaseMojo.java:99)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

```

**Comment by stoicflame** [comment]
Hmmm... Interesting. So it looks like they did some module repackaging.

I'm happy to entertain any suggested fixes.

**Comment by stevenschlansker** [comment]
It looks like the `com.sun.tools` and `com.sun.source` namespaces, that were never public, are now forbidden to use.

The immediate problem might be fixed simply:
```diff
diff --git a/core/src/main/java/com/webcohesion/enunciate/Enunciate.java b/core/src/main/java/com/webcohesion/enunciate/Enunciate.java
index d84d06806..25b940ab9 100644
--- a/core/src/main/java/com/webcohesion/enunciate/Enunciate.java
+++ b/core/src/main/java/com/webcohesion/enunciate/Enunciate.java
@@ -56,6 +56,7 @@ import javax.tools.DiagnosticCollector;
 import javax.tools.JavaCompiler;
 import javax.tools.JavaFileObject;
 import javax.tools.SimpleJavaFileObject;
+import javax.tools.ToolProvider;
 
 import com.sun.tools.javac.api.JavacTool;
 import com.webcohesion.enunciate.api.AggregatedApiRegistry;
@@ -684,7 +685,7 @@ public class Enunciate implements Runnable {
         sources.add(new URLFileObject(sourceFile, encoding));
       }
 
-      JavaCompiler compiler = JavacTool.create();
+      JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
```
but that leads to more restricted API uses for determining source element locations, and it wasn't immediately obvious what the right replacement is.

**Comment by stevenschlansker** [comment]
Temporary workaround: use `java --illegal-access=warn` will allow enunciate to continue to work for now, but will not be possible in future releases.

**Comment by kingds** [comment]
Has anyone had any luck with getting the maven plugin working with JDK 16? I tried adding the following to my plugin configuration:
```  
<compilerArgs>
   <arg>--illegal-access=warn</arg>
</compilerArgs>
```
... but still encountered the same error. I'm not a maven whiz, I'm guessing the issue is that this argument needs to be set at runtime not compilation. 

Also, I think `java ---add-exports jdk.compile/com.sun.tools.javac.api=ALL-UNNAMED` would be the more permanent workaround.

**Comment by stevenschlansker** [comment]
You need to set it on the `java` process, it is not a compiler argument.  With maven that is something like `MAVEN_OPTS=--illegal-access=warn mvn install`

**Comment by kingds** [comment]
@stevenschlansker that worked, thanks! For anyone else trying to run on JDK 16 on Windows, you can do the following before running the maven build:
`set MAVEN_OPTS=--illegal-access=warn` or `set MAVEN_OPTS=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED`.

**Comment by stoicflame** [comment]
I spent some time looking at this today. Many thanks to the comments and solutions offered here. I've [applied the above suggestions to the `enunciate-sample`](https://github.com/stoicflame/enunciate-sample/commit/a09dba6712de7011cb44c7e6f9e4b769fdc0c840) app and confirmed it works well with JDK 16 through 18. 

I also spent some time working at trying to change those illegal access points in the code. The problem is that I still need to keep support for JDK 8 to support slower adopters (including my own employer). I couldn't figure out how to change the code using JDK 8 in a way that isn't illegal in JDK 16+ because Enunciate uses a lot of the illegal access points to determine things like source position and other source-specific information as noted by @stevenschlansker .

My conclusion is that until the project is ready to move on from support for JDK 8, the solutions suggested here in this thread are going to have to suffice.

I'll keep this issue open until I can remove those illegal access points in a future build, and if anybody comes to a different conclusion I'd love to hear from you. Thanks again!

**Comment by sco0ter** [comment]
I can't get it working with JDK 17.

I set

MAVEN_OPTS=--illegal-access=warn

Maven then says:
`OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0`

Should actually also work with (but doesn't):
```
<compilerArgs>
                            <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
                            <arg>-J--illegal-access=warn</arg>
</compilerArgs>
```

**Comment by antonioortizpola** [comment]
@sco0ter, I tried with @stoicflame changes and it worked for my project using Amazon Corretto 17.

Just added the `jvm.file` in `.mvn` in the base folder of the project, but still hopping for a better solution.

**Comment by sco0ter** [comment]
Yes I could make it work with the config file as well.
Settings in pom.xml didnt work though.

**Comment by sklipnoty** [comment]
Yep same problem. JDK 17 is LTS, decent support would be great!

**Comment by tiguchi** [comment]
Here's the workaround for Gradle projects. The proposed JVM arguments can be added to `gradle.properties` as follows:

```properties
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```

**Comment by stoicflame** [comment]
Started work on Enunciate 2.15 and this was my first issue.

2.15 will finally drop support for Java 8 and move to the new compiler API. 

Current snapshot from `HEAD` at 530aad9ad has these provisions applied and no longer requires the `--add-exports` workaround to work with Java 17.

**Comment by nfalco79** [comment]
do you place some release to be able to build with Java 17 LTS?
