### ISSUE TITLE
javax.jws => jakarta.jws => no documentation generated

### ISSUE THREAD

**Issue by sco0ter** [stoicflame/enunciate#1122]
I switched from javax.jws.* to jakarta.jws.* but since then, no documentation is produced anymore.

It seems like the "jakarta" issue is partially fixed, but obviously not for all jakarta dependencies:

#1044
#1102
#1110

I use these import for my SOAP service:

```
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.jws.soap.SOAPBinding.Style;
```

jakarta.xml.soap-api:3.0.0
jakarta.jws-api:3.0.0

Enunciate prints:
```
[INFO] [ENUNCIATE] Enabled modules: [docs, jaxb, jaxws]
[WARNING] [ENUNCIATE] No documentation generated: there are no data types, services, or resources to document.
```

**Comment by stoicflame** [comment]
Okay, thanks for the report. I'll add support for `jakarta.jws` annotations.

**Comment by stoicflame** [comment]
I've decided to tackle the move from Java EE to Jakarta EE as a new release that will _drop_ support for Java EE (i.e. `javax.*` packages). This will allow me to not have to maintain support for both Java EE and Jakarta EE at the same time.

As such, this issue will need to move to `2.16.0` which is where I plan to implement this change.

**Comment by stoicflame** [comment]
Linked to #1149

**Comment by vghero** [comment]
We're facing a similar issue with our REST APIs where the constraint column in the generated docs is missing now when switching to jakarta based libraries due to Spring Boot 3.0 and its dependencies.

**Comment by simonDeHero** [comment]
hey there, i created a small example to show the issue in Spring Boot 3, mentioned by @vghero . play around with the `Parent` object. the constraints are rendered, if the `@NotNull` is enabled/existing. otherwise no constraints at all. don't look at the inheritance there. this was my initial thought. but i think, not related :-) 
(make sure, that your maven uses the `.mvn/jvm.config`!)
[flaky-constraint-rendering-spring-boot-3-jakarta.zip](https://github.com/stoicflame/enunciate/files/10390656/flaky-constraint-rendering-spring-boot-3-jakarta.zip)

i debugged the BeanValidationUtils, and i saw that the jakarta validations are existing there already. nice! but somehow the `describeConstraints()` is not even called, if `@NotNull` is not existing in the object.

we use enunciate 2.14.0.

**Comment by simonDeHero** [comment]
hey there,
i took another look, and for me, this change here in `com.webcohesion.enunciate.util.BeanValidationUtils#hasConstraints` works:
```
          if (pckg instanceof PackageElement) {
            boolean isJavaxConstraint =
                    ((PackageElement) pckg).getQualifiedName().toString().equals("javax.validation.constraints");
            boolean isJakartaConstraint =
                    ((PackageElement) pckg).getQualifiedName().toString().equals("jakarta.validation.constraints");
            if (isJavaxConstraint || isJakartaConstraint) {
              return true;
            }
```

@stoicflame WDYT? good enough, or am i missing some other places? where could i create a test for it? so that i can make a PR :-)

**Comment by stoicflame** [comment]
Seems good to me. If you want to put together a PR against `master`, I'll be happy to merge it.

**Comment by stoicflame** [comment]
`2.16` drops support for "old" APIs and moves completely to `jakarta.*`.

**Comment by stoicflame** [comment]
[Enunciate 2.16.1](https://github.com/stoicflame/enunciate/releases/tag/v2.16.1) has been released.
