### ISSUE TITLE
Data types referenced in collections, arrays, or type variables aren't being auto-discovered.

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#131]
In my generated documentation, some DTO's aren't actually included in the documentation (and I assume they wouldn't be included in any client library either).

When these DTO's aren't included, REST operations will say this for parameters and return types:
 * object (JSON)
 * array of object (JSON)
 * custom (XML)

Is there a way to enable some kind of debug-output from the generation? I can't see any reason to why these DTO's shouldn't be included.

Thanks!

PS: Questions like these doesn't feel appropriate to submit issues for really. Maybe we should add a [gitter.im](https://gitter.im/)-chat to this repository?

**Comment by stoicflame** [comment]
So there isn't any debug output describing why something was _not_ included.

In this particular case, the problem seems to happen in the `addReferencedDataTypeDefinitions` method, [JaxrsModule, line 123](https://github.com/stoicflame/enunciate/blob/v2/jaxrs/src/main/java/com/webcohesion/enunciate/modules/jaxrs/JaxrsModule.java#L123) which iterates through the return type and parameters of a resource method and adds each data type to the module.

If you can describe a way for me to reproduce the problem, I'd be happy to dig into it.

**Comment by anton-johansson** [comment]
I don't think so, no. I'll check again tomorrow.

A colleague of mine got a theory that it's because some data types are only used in responses or requests in generic ```Lists```. I haven't verified this theory yet, but it seems to match our case atleast. I'll try adding a REST-method with that particular data type as a normal response or request body (i. e. without a generic ```List```).

**Comment by stoicflame** [comment]
> A colleague of mine got a theory that it's because some data types are only used in responses or requests in a generic Collection.

Oh yeah. That's probably what's going on. I'll work on fixing that.

**Comment by stoicflame** [comment]
Okay, I've applied a fix at 043b87a.

I'm going to rename this issue and close it out. Milestone 4 should be available shortly.

**Comment by anton-johansson** [comment]
Very nice work!

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.
