### ISSUE TITLE
Splash package 

### ISSUE THREAD

**Issue by theCompanyDream** [stoicflame/enunciate#150]
Hello Enuciate team I'm having some issues trying to add a splash package to the generated documentation. My company just migrated from enunciate 1x to 2x and noticed that there isn't an option for splash package was it removed?

**Comment by stoicflame** [comment]
```xml
<enunciate>
  <description package="com.mycompany.mypackage"/>
</enunciate>
```

**Comment by martin-bootstrap** [comment]
Hi. This solution isn't working for me. Instead of my splash content, I see the maven pom project description. 

Using 
`<groupId>com.webcohesion.enunciate</groupId>`
` <artifactId>enunciate-maven-plugin</artifactId>`
` <version>2.5.0</version>`

Please advise. Thanks.

**Comment by stoicflame** [comment]
@martin-bootstrap, I'm afraid I can't reproduce the problem you're seeing. For example, check out the "step5" branch of [the sample app](https://github.com/stoicflame/enunciate-sample).

If you can provide me a way to reproduce the issue, feel free to open up a new issue with the details.

**Comment by sfussenegger** [comment]
I had this issue with 2.6 using a `package-info.java` in an otherwise empty parent package of the API and model classes: I had included `org.example.api` and `org.example.model` with description in `org.example`.

adding an include to `api-classes` did not solve the problem. moving the `package-info.java` to `org.example.api` did.
