### ISSUE TITLE
Link to Swagger UI is broken?

### ISSUE THREAD

**Issue by nuevedientes** [stoicflame/enunciate#164]
When I generate the docs in Enunciate 2.0 on the main page that is generated there is a link to Swagger UI.  "You may also enjoy the Swagger UI provided for this API."

The link takes me to myservice/ui/ and I get a blank page (debugging shows a 404). When I go to  myservice/ui/index.html I get a page with a nice swagger heading, but it shows a message that says, "Can't read swagger JSON from myservice/ui/index.html/swagger.json"

Is there a trick to getting swagger to work?

**Comment by nuevedientes** [comment]
Oops, just found this page: https://github.com/stoicflame/enunciate/wiki/Module-Swagger
I'll try that & come back!

**Comment by nuevedientes** [comment]
Ok yeah, I think this is a bug on your end... When I explicitly go to myservice/ui/index.html page I can type in the url to swagger.json and see the swagger docs.  But it's not coming up automatically when I just go to myservice/ui.

**Comment by stoicflame** [comment]
Yes... I ran into this problem when I was working on the 2.0 Swagger module.

Is there a reason why you get a blank page at "/myservice/ui/"? Do you need to add "index.html" to your `welcome-file-list` in your `web.xml`?

Here's the conundrum:

* The index page needs to be able to find the "swagger.json" file. 
* By default, the index page says to load it by relative URI "swagger.json".
* If the request is for "ui/index.html", the URI gets resolved as "ui/index.html/swagger.json".
* So I decided to link to "ui/" so that the swagger.json gets resolved correctly, but its success depends on the "index.html" page being served up upon a request to "ui/"

Well, maybe there's a way to hack the Swagger javascript to do the right thing whether you're at "ui/" or "ui/index.html". I'll see what I can find out.

**Comment by stoicflame** [comment]
Okay, I did some javascript hacking at fb968b9 and got it to work. It's available in the latest snapshot build.

**Comment by darmbrust** [comment]
Should this fix be in the 2.2.0 release?  I'm not very experienced with enunciate, so I may be doing something wrong... but I'm still seeing what looks like this issue.

**Comment by darmbrust** [comment]
for reference, I'm just trying to test it on my local dev box - opening up the index.html from within the target folder of my build.

Clicking on the swagger link results in an error like this:

fetching resource list: file:///E:/EclipseWorkspaces/ISAAC2/ISAAC-rest/target/isaac-rest-1.0-SNAPSHOT/ui/index.html/file:///E:/EclipseWorkspaces/ISAAC2/ISAAC-rest/target/isaac-rest-1.0-SNAPSHOT/ui/swagger.json

If I put ../swagger.json in the location box - then it mostly works (I still get an error marker at the bottom)

**Comment by stoicflame** [comment]
It won't work from the filesystem. Your browser won't read the swagger.json file per its cross-domain policy. You'll need to bring up a server on your local box for Swagger UI to function. Consider [Cargo](https://codehaus-cargo.github.io/cargo/Home.html) or something of the like.

**Comment by darmbrust** [comment]
Hmm - well, not sure how much of it is working correctly (I get an error marker at the bottom), but adding this else if statement above the else section you added in this thread causes it to mostly work:
	  
          else if (document.location.href.substring(0, 5) === "file:") {
		url = "../swagger.json";
	  }
