### ISSUE TITLE
datatype-detection="local" not honoring excluded patterns using CXF

### ISSUE THREAD

**Issue by waytooearly** [stoicflame/enunciate#181]
```xml
<api-classes>
<include pattern="com.my.class.*" />
<exclude pattern="com.my.class.Exclude*Request" />
</api-classes>
<modules>
        <c-xml-client disabled="true" />
        <csharp-xml-client disabled="true" />
        <docs disableRestMountpoint="true" freemarkerTemplate="documentation/src/main/resources/docs.fmt" css="documentation/src/main/resources/styles.css" />
        <gwt-json-overlay disabled="true" />
        <idl disableWadl="true" />
        <jackson honorJaxb="true" datatype-detection="local"  />
        <jackson1 disabled="true" />
        <java-json-client disabled="true" />
        <java-xml-client disabled="true" />
        <jaxrs groupBy="path" datatype-detection="local" />
        <jaxws disableCompile="true" />
        <obj-c-xml-client disabled="true" />
        <php-json-client disabled="true" />
        <php-xml-client disabled="true" />
        <ruby-json-client disabled="true" />
        <swagger disabled="true" />
    </modules>
```

This results in the exclusions not being honored.  Using passive honors the exclusions, but doesn't include all the necessary classes required for the documentation.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
So this works for me. "local" is the datatype detection strategy in the [full edge cases example](https://github.com/stoicflame/enunciate/tree/master/examples/full-api-edge-cases), and the "exclude" in the [enunciate.xml](https://github.com/stoicflame/enunciate/blob/master/examples/full-api-edge-cases/enunciate.xml#L5) file is getting correctly applied.

I wonder if the `Exclude*Request` classes are getting included because they're being _referenced_ by a resource method? Enunciate has to pull in classes that are being referenced by classes that are included, or else the compile will fail. If you're looking to exclude certain methods or facets, you'll need to use the [facets mechanism](https://github.com/stoicflame/enunciate/wiki/Facets).

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)

**Comment by roman-voropaev** [comment]
Is there way to exclude even referenced data classes? For example in one of my JAX-RS methods I accept binary content as InputStream. And referencing java.io.InputStream is definitely not desired.
![stream](https://cloud.githubusercontent.com/assets/1194340/12442906/d5471d42-bf4b-11e5-97a1-0884d6aad4ca.png)

**Comment by roman-voropaev** [comment]
Oh, found this https://github.com/stoicflame/enunciate/issues/247 Thanks!
