### ISSUE TITLE
support for @SampleRequest and @SampleResponse

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#190]
Hi,

I noticed that there used to be two annotations for generating examples, how come those don't exist anymore? Is there an alternative I can use?

Thanks!

**Comment by stoicflame** [comment]
The feature didn't make the cut to 2.0. There's not a current alternative, but I'll keep this issue around as a feature request to get it back in.

**Comment by bogdanzurac** [comment]
Was looking for this as well. It's not critical, but I remember being a nice feature from 1.x.

**Comment by hskigithub** [comment]
+1

**Comment by Sheshagiri** [comment]
+1

**Comment by stoicflame** [comment]
At 8c1eff7, docs now include example request/response. No annotations needed.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by vguna** [comment]
The new request/response JSON display of 2.6.0 is really nice. But it would be great if these examples could be overridden by a handmade version of the json, if the generated one is maybe not suitable. So I like the idea of `@SampleRequest/Response`. But I'm not sure how the json could be easily provided to the annotations. Especially when they're more complex.

**Comment by stoicflame** [comment]
`@SampleRequest` and `@SampleResponse` never carried the ability to specify the example body; it was just a marker for _whether_ to include a sample request/response. The `@DocumentationExample` annotation was intended to customize the request/response body. If there are deficiencies there, I'll need a separate issue detailing those deficiencies.

Unfortunately, it's quite not as simple as "overriding" the examples with a "handmade" version because you have to think about other media types (e.g. XML).

**Comment by vguna** [comment]
Hm I see. Haven't thought of the other media types.  I think about it in more detail and maybe come back in a separate issue as suggested.  Thanks!
