### ISSUE TITLE
JacksonModule: @Typehint with interface as datatype

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#210]
Hi!
I'd like to use `@TypeHint` with an interface, but keep getting **"... isn't a potential Jackson type because it's not a class."** as an error. Is there a reason why interfaces are explicitly not considered in the JacksonModule?

Thanks!

**Comment by stoicflame** [comment]
Thanks for the report. I'll track it as an issue and assign it to 2.2.

**Comment by stoicflame** [comment]
Please clarify how you'd like to use `@TypeHint`. The message about "isn't a potential Jackson type" means that the interface isn't going to show up in the JSON documentation. That's a good thing because you don't want the interface to show up in the docs, you want the "hinted" class to show up.

So what exactly isn't working here?

**Comment by stoicflame** [comment]
I'm going to close this as working as designed. I'd be happy to re-open this if needed.
