### ISSUE TITLE
Dependencies with provided scope break build in module setup

### ISSUE THREAD

**Issue by xpapad** [stoicflame/enunciate#236]
I am using a setup described in https://github.com/stoicflame/enunciate/issues/234

My module has a dependency on *javax.servlet:javax.servlet-api* with *provided* scope. This causes the enunciate 2.1.1 maven plugin to break my build:

```
[WARNING] [ENUNCIATE] [javac] [ERROR] com.webcohesion.enunciate.Enunciate$URLFileObject[file:/home/xenofon/workspace/darwin/csb/modules/csb-module-csadmin/target/csb-module-csadmin-1.0-SNAPSHOT-sources.jar!/com/company/saas/csadmin/rest/UsersRestService.java]:6:26 /home/xenofon/workspace/darwin/csb/modules/csb-module-csadmin/target/csb-module-csadmin-1.0-SNAPSHOT-sources.jar!/com/company/saas/csadmin/rest/UsersRestService.java:6: error: package javax.servlet.http does not exist
[WARNING] [ENUNCIATE] [javac] /home/xenofon/workspace/darwin/csb/modules/csb-module-csadmin/target/csb-module-csadmin-1.0-SNAPSHOT-sources.jar!/com/company/saas/csadmin/rest/UsersRestService.java:6: error: package javax.servlet.http does not exist
[WARNING] [ENUNCIATE] [javac] import javax.servlet.http.HttpServletRequest;
```

It works if I temporarily set scope to compile, but naturally this is not sustainable long-term.

**Comment by stoicflame** [comment]
Thanks for the report. 

It's Maven that's providing the list of dependencies to Enunciate, so I'll look into whether there's some way to ask Maven for the provided-scope transitive dependencies.

In the meantime, I'd suggest just adding the servlet-api as a provided-scope dependency to the module where Enunciate is applied. This might be a better solution than changing the scope to "compile".

**Comment by xpapad** [comment]
It's not a transitive dependency, it's explicitly declared in my parent (and module's) pom with *provided* scope.
I think the problem is that provided dependencies are not available in the classpath during assembly?

**Comment by stoicflame** [comment]
So I'm having a hard time reproducing this. When I set one of my dependencies to scope "provided", it gets picked up and included on the Enunciate classpath.

Maybe I'm not understanding the setup. Here's how I understand it, please correct me where I'm wrong:

* You've got the "csb-module-csadmin" module that contains the "UsersRestService" resource, which depends on the servlet-api jar.
* The servlet-api.jar is declared as scope "provided" in the "csb-module-csadmin" module.
* You've got another module (name not provided yet) that _depends_ on the "csb-module-csadmin" in which you're invoking Enunciate.
* This other as-yet-unnamed module does _not_ have servlet-api jar as part of its dependencies (scope "provided" or otherwise).

If this is the case, I don't see anything that can be done other than making sure that servlet-api.jar is included in the as-yet-unnamed module as scope "provided".

**Comment by stoicflame** [comment]
Please comment if needed; I'd be happy to re-open.
