### ISSUE TITLE
How can I overwrite the generated files?

### ISSUE THREAD

**Issue by guyh-tointv** [stoicflame/enunciate#293]
Hi,

It looks like enunciate does not overwrite existing HTML files. Is this possible?

I will try to explain:
Say I have an empty output folder named apiDocs, and I use enunciate to generate HTML files into that folder.

When I modify my source code, and generate again the HTML files, the files are not modified. I have to manually delete the folder, and only than execute enunciate to generate the file.

Is there an overwrite flag or something?

Thanks
H Guy

**Comment by stoicflame** [comment]
Enunciate should be detecting the changed source file. If you do verbose output (e.g. mvn -X), you should get a log statement that looks something like this:

"%s is up-to-date because its oldest file, %s, is younger than the youngest source file."

**Comment by guyh-tointv** [comment]
Hi,
Thanks for your answer.

I see the following message:
````
[DEBUG] [ENUNCIATE] c:\SpringSource\Workspace\Company\media\media-web\src\main\webapp\resources\apiDocs is up-to-date because its oldest file, c:\SpringSource\Workspace\Company\media\media-web\src\main\webapp\resources\apiDocs\css\style.css, is younger than the youngest source file.
[INFO] [ENUNCIATE] Skipping documentation source generation as everything appears up-to-date...
````

apiDocs is my output folder, and the oldest file (style.css), is not younger than the youngest source file.
What is the definition for "source file"?

Thanks
H Guy

**Comment by guyh-tointv** [comment]
I still cannot overwrite the generated files. Is there any way to disable this feature?

**Comment by stoicflame** [comment]
There's a bug that needs to be fixed.

Currrent workaround is to make sure to delete generated files before incoking Enunciate. (E.g. "mvn clean")

**Comment by guyh-tointv** [comment]
Understood. Thanks.

**Comment by nfalco79** [comment]
I fall in this issue.
I have a multi-module project. A parent with 2 submodules, enunicate is in `<reporting>` section.
The command line: `mvn clean package site site:deploy` never produces excepted documentation. The artifact produced is an empty index.html and it logs me
> [INFO] [ENUNCIATE] Skipping documentation source generation as everything appears up-to-date...

Debugging a lot I found the issue.
To understand if sources are updated compare their timestamp with the temporary enunciateConfig7636088136450061917.xml file generated during a maven phase in `{project.basedir}/target/enunicate/` (not clear why did not compare with actual date).
There are many method to load `EnunciateConfiguration` by reader, file, URL or inputstream. At the end the last one is really used to load configuration using apache `XMLConfiguration` API, in this manner you ensure that the inputstream is force to be UTF-8 and this is right.
But when you need to get the file back to obtain its timestamp you use `EnunciateConfiguration.getSource()` that returns the apache XMLConfiguration implementation and than call `getFile()` on it that is null because you load as InputStream. So the local variable `newestSourceTimestamp` is never initialise and by default is 0 and than `BasicGeneratingModule.isUpToDateWithSources()` fails its check.

**Comment by nfalco79** [comment]
It was hard make pull request that respects indentation.

**Comment by nfalco79** [comment]
This issue happens when you specify an enunciare.xml file.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
