### ISSUE TITLE
Documentation and inheritance

### ISSUE THREAD

**Issue by Fival85** [stoicflame/enunciate#375]
Hello again,

we have a new questien/problem:

How could you controll the documention of inherited fields?
We have this use-case:

```java
@XmlRootElement
public class B extends A{
	
	/**
	 * Returns A but destroys the world *evil*.
	 */
	@Override
	public String getFieldA() {
		return "boom";
	}
}
```

and 

```java
@XmlRootElement
public class A {
	private String fieldA;

	/**
	 * Returns field A.
	 * @return
	 */
	public String getFieldA() {
		return fieldA;
	}

	public void setFieldA(String fieldA) {
		this.fieldA = fieldA;
	}
	
}
```

In the documention we want to see the comment of the new overwritten field, but we still see the comment of overriden class A. Is there any possibility to get the documention of class B?

Background: We have some DTOS in a API-Modul which are used by the RMI and Hessian-Interface. We also want to use these DTOs at the REST-Api, but we dont want to have REST-Annotations, something like this or any other change in the original DTO. These changes (eg annotations), or changed comments for the rest call should be at the new inherited dto for the REST-API. So we have separated the REST-API and another APIs
Another usecase is the usage of an third party dto, where you want to override some docs..

Thank you

**Comment by stoicflame** [comment]
Maybe. I'll take a look.

**Comment by stoicflame** [comment]
Okay, I've spent quite a bit of time researching this.

I can confirm that Jackson uses the overridden/hidden accessor for (de)serialization, so it would make sense for Enunciate to also use the documentation of the overridden/hidden accessor.

However, by default, Enunciate's documentation includes type hierarchies, so it uses the documentation of the supertype (class `A` in the example above) because it generates that documentation outside the context of the subtype (class `B` in the example above). In other words, when it generates the documentation for the `fieldA` property, it does so in the context of class `A` and not class `B`.

However, Enunciate _does_ provide the ability to "collapse" type hierarchies. For example, if class `A` were annotated with `@com.webcohesion.enunciate.metadata.Ignore`, then Enunciate wouldn't generate any documentation for class `A` and `B` would be documented such that all the properties of `A` looked like they were properties of `B`.

At 4129bd7, I added the ability to globally collapse the type hierarchy via the config, like this:

```xml
<enunciate>
  <modules>
    <jackson collapse-type-hierarchy="true"/>
```

Or, if using Jackson 1:

```xml
<enunciate>
  <modules>
    <jackson1 collapse-type-hierarchy="true"/>
```

**Comment by Fival85** [comment]
Hello again,

i tried the Ignore-Annotation of Enunciate. It does not have any effect to me. 

I have test it with Enunciate 2.2 and the jboss-example project:

So i cloned the Person-DTO "Person2" which override the gender-field by getter and setter:
`@XmlRootElement
public class Person2 extends Person {

 

  /**
   * The gender of a person. overriden getter
   *
   * @return The gender of a person.
   */
   @Override
  public Gender getGender() {
    return super.getGender();
  }

  /**
   * The gender of a person. overriden setter
   *
   * @param gender The gender of a person.
   */
   @Override
  public void setGender(Gender gender) {
    super.setGender(gender);
  }

}`

This type i used in the PersonService as return-type (TypeHint)
` @PUT
  @Path ("/pedigree/person")
  @TypeHint(Person2.class)
  public Person storePerson(Person person) {
    return person;
  }`

But in the dokumentation i see the comment of original-Person and i could see the inheritance from person2 to person. The changed code is in the zip-file. 

[enunciate-jboss-examlple.zip](https://github.com/stoicflame/enunciate/files/281162/enunciate-jboss-examlple.zip)

Here you could see the dokumentation result of person2.class:
![person2_doku](https://cloud.githubusercontent.com/assets/11659931/15530313/f1f40aca-2253-11e6-880d-9adf4dfe489d.JPG)

There is no comment of the person2.class. Instead all comments are from the original-class.

Is there a bug or make i something wrong?

Thank you

**Comment by stoicflame** [comment]
Yeah, it might not have been fully working yet. I fixed that, and have confirmed it's working in the latest snapshot version 2.4.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
