### ISSUE TITLE
Javadoc on jax-rs resource interface doesn't show up in documentation

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#391]
Hi.

I've documented a JAX-RS resource interface with javadoc for the interface itself. Describing what it's all about. It doesn't show up in the documentation at all - as it seems :).

It looks like that the doc generation process has the information about the interfaces, as it groups the endpoints according to them. Is it possible to add the javadoc from the interface above the actual endpoints description (PUT, GET etc.)?

**Comment by stoicflame** [comment]
Just trying to think this through.

So Enunciate uses the documentation where the annotations are found. So whatever method the `@GET`, `@POST`, etc. method is found will be used for the documentation. Likewise, whatever class the `@Path` is found will be used for the documentation since that's the actual class that Jersey will use to implement the API.

You're saying you'd like Enunciate to include documentation for (presumably all) implemented interfaces? What do you suggest happens when the class implements multiple interfaces? Does it choose one? Would that cause any unintended side-effects for current users?

**Comment by stoicflame** [comment]
Fixed at dac9a5f. The [JavaDoc spec specifies the algorithm](http://docs.oracle.com/javase/6/docs/technotes/tools/solaris/javadoc.html#inheritingcomments).

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
