### ISSUE TITLE
Invalid swagger produced when endpoints return different content

### ISSUE THREAD

**Issue by nomisvai** [stoicflame/enunciate#509]
OpenApi issue:

https://github.com/OAI/OpenAPI-Specification/issues/146

Enunciate generates an invalid swagger.json file when the following pattern occurs (same path, different "Produces" annotation):

```java
@Path("/myResource")
@Produces("text/plain")
public class SomeResource {
    @GET
    public String doGetAsPlainText() {
        ...
    }

    @GET
    @Produces("text/html")
    public String doGetAsHtml() {
        ...
    }
}
```

I'm not sure if anything can/should be done enunciate side (maybe favor application/json and drop the others until the openapi spec supports it)... 

Extending the Ignore annotation so that we could exclude some endpoints from being processed by the swagger module might also be an option:  @Ignore(module=swagger)

**Comment by stoicflame** [comment]
Thanks for the report.

I think, for now, I'm not going to do anything about it until the 3.0 spec comes out. The generated JSON is invalid because of the duplicate method getting added to the [path item object](http://swagger.io/specification/#pathItemObject), but it doesn't cause the Swagger UI to fail, so no harm done.

I'm happy to re-open if my assumption about "no harm done" is incorrect.
