### ISSUE TITLE
Required headers

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#530]
Hi.

Is there a way to mark headers as required? E.g. when an auth token is required.
Currently using:

`@RequestHeader Authorization The required authorization <code>Bearer</code> token.`

What about

`@RequiredRequestHeader`

:). Or 

`@RequestHeader Authorization required The required authorization <code>Bearer</code> token.`

But that would break backwards compatibility and it is fuzzy to guess whether it's the required flag or just documentation. The same as checking documentation if "required" is mentioned there.

I'm not very familiar with javadoc tags and parameterization...

Any ideas?

**Comment by stoicflame** [comment]
Seems like a reasonable request, but it's really just an enhancement request for [jax-doclets](http://fromage.github.io/jax-doclets/docs/0.10.0/html/), no? I'd suggest opening an issue or an enhancement request for them.

I could consider enhancing `@com.webcohesion.enunciate.metadata.rs.RequestHeader` to support a `required` method. Would that help?

**Comment by vgcookies** [comment]
I can try ;).

For now I'm using javadoc only for documentation to keep my code clean from enunciate compile dependencies (sorry for that ;)), but that totally makes sense. I could use it as a "workaround" then...

**Comment by vguna** [comment]
I can try ;).

For now I'm using javadoc only for documentation to keep my code clean from enunciate compile dependencies (sorry for that ;)), but that totally makes sense. I could use it as a "workaround" then...

**Comment by vguna** [comment]
Hm. Seems that this project is no longer maintained. Issues are from 2014 :(...

**Comment by stoicflame** [comment]
Since the definition of that `@RequestHeader` JavaDoc tag isn't maintained here, I just don't feel comfortable arbitrarily changing it.

Anyway, I'm not sure how I'd change it even if I _could_. It seems like the very nature of JavaDoc tags limits it's capabilities. It's really just a tag with a string after it. Even if we came up with some way to parse the string to add a "required" indicator to it, I bet it wouldn't take long to come up with other indicators we'd want (minLength, NotNull, min, max, regexp, etc.). 

There's just no standard way to tag JavaDoc tags. So I think I'm comfortable saying that if you want more powerful metadata capabilities, use annotations.
