### ISSUE TITLE
Below parameters are not working

### ISSUE THREAD

**Issue by rajneekanth** [stoicflame/enunciate#605]
Below parameters are not working.

@Request URL https://pprgw2gapimgmt.azure-api.net/entintbridge/createTrip

I want to show Request Parameters in the generated swagger UI, but no luck. I tried below ways. 

	 * @RequestParam IDToken ADFS token to authenticate the user on Way2Go
	 * @param name IDToken ADFS token to authenticate the user on Way2Go
	 * @RequestParameter UserName Login ID of the User
	 * @documentationExample documentationExample male
	 * @label label PersonRelativeAge
	 * @RequestParameter Domain Domain of the AD on which the user is authenticated
	 * @inputWrapped IDToken ADFS token to authenticate the user on Way2Go

can you help me here. Thank you.

**Comment by stoicflame** [comment]
What does the Java method signature look like?

**Comment by rajneekanth** [comment]
Thanks for your quick reply. method signature looks like this.

public String tripDetails(String tripDetailsReq)

tripDetailReq is a JSON object, it has few details like token, username, domain etc. 

by the way, i have used like below. 
@RequestHeader UserName Login ID of the User

in the output, it is showing as "UserName Header Login ID of the user". is there any way to replace that header to string?

and how can i show the URL?

once again, thank you very much for your reply and help.

**Comment by stoicflame** [comment]
I'll have to look into it further by setting up a project and trying it out myself.

If you'd like to attach a patch (or create a branch) of the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) that exposes the issue, that would help speed up the process.

**Comment by rajneekanth** [comment]
Hi,

Pasting a sample code below. Thank you. 

@Path("/")
public class Client {
	/**
	 * 
	 * @RequestURL www.gmail.com
	 * 
	 * @RequestHeader IDToken ADFS token
	 * @RequestHeader UserName Login ID of the User
	 * @RequestHeader Domain Domain of the AD on which the user is authenticated
	 * @RequestHeader orgId Organization ID of the user's Company
	 * @RequestHeader orgToken Token for validating the User's Organization
	 *
	 * @RequestResource url bbc.com
	 * @Resource url abc.com
	 * @ResourceLabel url xyz.com
	 * @Host abc.com
	 * @host bbc.com
	 * 
	 * @param name IDToken ADFS token to authenticate the user
	 * @RequestParameter UserName Login ID of the User
	 * @documentationExample documentationExample male
	 * @label label PersonRelativeAge
	 * @RequestParam Domain Domain of the AD on which the user is authenticated
	 * @inputWrapped IDToken ADFS token to authenticate the user
	 * 
	 */
	@POST
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	@Path("myDetails")
	public String myDetails(String myDetailsReq) {
		return response;
	}
}

**Comment by rajneekanth** [comment]
hi, any update on this ? Thanks

**Comment by stoicflame** [comment]
Here's the screenshot of the method provided above:

![screenshot](https://cloud.githubusercontent.com/assets/145838/24559143/d7897c7e-15fa-11e7-9d2b-74ec7b1d8665.png)

Here are the notes:

### `@RequestURL`

No idea what this is. Enunciate doesn't support this annotation and I can't find any information about what it's supposed to do.

### `@RequestHeader`

Working as designed. See the screenshot.

### `@RequestResource`

No idea what this is. Enunciate doesn't support this annotation and I can't find any information about what it's supposed to do.

### `@Host`

No idea what this is. Enunciate doesn't support this annotation and I can't find any information about what it's supposed to do.

### `@RequestParameter`

No idea what this is. Enunciate doesn't support this annotation and I can't find any information about what it's supposed to do.

### `@documentationExample`

Per [the docs](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#documentationexample-javadoc-tag), not applicable to a resource method. Working as designed.

### `@label`

Per [the docs](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#label-javadoc-tag), not applicable to a resource method. Working as designed.

### `@RequestParam`

No idea what this is. Enunciate doesn't support this annotation and I can't find any information about what it's supposed to do.

### `@inputWrapped`

Incorrect usage of the tag because it needs to resolve to a type definition. See [the docs](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#inputwrapped-javadoc-tag). Enunciate correctly ignores this tag.
