### ISSUE TITLE
Alternative format (at most 1 underscore) for generated operationId

### ISSUE THREAD

**Issue by Mykro** [stoicflame/enunciate#652]
There's a prominent bug ("feature") in Visual Studio 2017's Rest Client Code Generator which uses a swagger.json as input.  It can parse values with one but not two or more underscore symbols.   Likelihood of it being fixed before Visual Studio 2019 is low.

The Swagger spec itself gives examples such as: "operationId": "getPetsById", and other Swagger-based frameworks such as Swashbuckle use a similar CamelCase format e.g. "Contact_getPetsById".

I know the underscores are within Swagger spec but is it possible for Enunciate to have an option to generate operationId with only zero (or one) underscores?

**Comment by Mykro** [comment]
More information.  The Visual Studio generator is based on Autorest, which still in the latest version is describing the one-underscore limit as a "Noun_Verb" convention rather than considering it to be a bug. 

```
PM> AutoRest.exe -Input [path]\enunciate-output\apidocs\ui\swagger.json -OutputDirectory [path]
Code generation failed.
AutoRest.exe -Input [path]\enunciate-output\apidocs\ui\swagger.json -OutputDirectory [path]
AutoRest.exe : ERROR: OneUnderscoreInOperationId: Only 1 underscore is permitted in the operation id, following Noun_Verb conventions.
```

**Comment by stoicflame** [comment]
Finally getting around to looking at this.

The [Swagger Spec](https://swagger.io/specification/#operationObject) clearly states that `operationId` needs to be unique, and if I use the Classname_Methodname convention, I have no guarantee that it will be unique. In fact, the implementation of the slug is as noisy as it is today because of issues like #322 that require that uniqueness.

For now, I'm going to close this as "will not fix".

The workaround is to provide a custom `swagger.fmt` file such that instead of:

```
"operationId" : "${method.slug?json_string}",
```

on line 197, you can use something like:

```
"operationId" : "${method.resourceMethod.parent.simpleName}_${method.resourceMethod.simpleName}",
```

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
