### ISSUE TITLE
external documentation example configuration

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#681]
I can use `@DocumentationExample` to provide a documentation example to a specific field. However, it would be nice if this can be done on a per-type basis. Is this possible? I couldn't find anything about it.

My use case for it is `ZonedDateTime`. Instead of showing `"..."` in the examples, I would like to always show something like `2017-06-27T15:47:55.191Z`. I wouldn't want to add this annotation to all my `ZonedDateTime` fields.

**Comment by anton-johansson** [comment]
@stoicflame: Any guide on this wiki for how to utilize this? :)

**Comment by stoicflame** [comment]
Just like you suggest above; annotate `ZonedDateTime` with `DocumentationExample`.

**Comment by anton-johansson** [comment]
But what if the type is a JDK class (just like `ZonedDateTime`)?

**Comment by stoicflame** [comment]
I see. I didn't recognize that JDK class.

So you're asking for some kind of configuration option or package-level metadata that can be scoped to an external class.

It's trickier than it sounds because each data module produces its own example, so it would need to be scoped by type per module. E.g. what if the XML example was different from the JSON example because JAXB (de)serialized the type differently than Jackson?

So it would have to be something like:

```xml
<enunciate>
  <modules>
    <jaxb>
      <examples>
        <example type="java.time.ZonedDateTime" example="...xml example..."/>
      </examples>
    <jaxb>
    <jackson>
      <examples>
        <example type="java.time.ZonedDateTime" example="...json example..."/>
      </examples>
    </jackson>
  <modules>
</enunciate>
```

Is that what you were thinking?

**Comment by anton-johansson** [comment]
Yeah. Package-level meta-data would be nice, to avoid XML-configuration. However, annotations on `package-info.java` arean't recursive, right? So it would be a hassle to keep all my packages properly annotated.

I think your XML-configuration example would be the way to go.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
