### ISSUE TITLE
Why doesn't @link work in certain settings

### ISSUE THREAD

**Issue by LittleBarn** [stoicflame/enunciate#728]
I am aware of #703 and #174
My question is how come it doesn't work in certain places? Am I doing anything wrong? For example I am trying to use it in a @ResponseHeader like so:

```java
/**
 * @HTTP 200 successfully completed
 * @HTTP 202 Job did not complete quickly and was made into a background job
 * @HTTP 404 The Directory was not found
 * @ResponseHeader Location If the job does not complete immediately, this will contain the
 * location in the {@link AsyncApi} where you can check the progress of the background job
*/
```

**Comment by stoicflame** [comment]
Finally got around to looking at this.

JavaDoc elements that are used to define pieces of the API are processed before any documentation gets generated. So since these particular JavaDoc elements (`@ResponseHeader`, `@RequestHeader`, `@HTTP`, `@HTTPWarning`, etc.) are actually modifying the core API model, they get processed _below_ any documentation context and therefore have no context to resolve the link.

To say that another way, there's no way for the engine to know at the time of processing these particular JavaDoc elements that the link to `com.mycompany.MyClass` will some time later resolve to a link that looks like `resource__myclass_get__id.html`.

It's not impossible to push the resolution of these JavaDoc elements down to each level that is interested in them, where a link resolution context might be available. But to do so would be a lot of work and might have implications for future modules that rely on the model to be fully established before any processing is picked up. If there's enough interest in doing this work, you're welcome to open up another issue to track it.
