### ISSUE TITLE
Build fails with 2.10.0

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#766]
Just gave 2.10.0 a testdrive - coming from 2.9.1 and this results in a broken maven build:

```
[INFO] Reflections took 767 ms to scan 101 urls, producing 373 keys and 373 values 
[WARNING] [ENUNCIATE] [javac] [ERROR] null:-1:-1 error: cannot access org.springframework.hateoas.ResourceSupport
[WARNING] [ENUNCIATE] [javac] error: cannot access org.springframework.hateoas.ResourceSupport
[WARNING] [ENUNCIATE] [javac]   class file for org.springframework.hateoas.ResourceSupport not found
[WARNING] [ENUNCIATE] [javac]   Consult the following stack trace for details.
[WARNING] [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.springframework.hateoas.ResourceSupport not found
```

Switching back to 2.9.1 works fine.
Looks like https://github.com/stoicflame/enunciate/issues/665.

Adding spring hateos to the normal dependencies fixes the build, but this dep is not used at all (explicitly) within the actual project. So I wonder why this is needed now :)?

**Comment by stoicflame** [comment]
Confirmed.

I don't know why spring-hateoas is required now. If anyone finds an answer, please comment here.

**Comment by Blackbaud-MikeLueders** [comment]
I don't understand enunciate yet enough to have a solution but I believe I understand the root cause.   
```
09:56:28.296 [DEBUG] [org.gradle.api.Task] Detected API Types: [
...
 org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration.EndpointResource
...
]
...
09:56:28.880 [WARN] [org.gradle.api.Task] [javac] [loading ZipFileIndexFileObject[/Users/mike.lueders/.m2/repository/org/springframework/boot/spring-boot-actuator/1.4.1.RELEASE/spring-boot-actuator-1.4.1.RELEASE.jar(org/springframewor\
k/boot/actuate/autoconfigure/EndpointWebMvcHypermediaManagementContextConfiguration$EndpointResource.class)]]
```
The class $EndpointResource extends `import org.springframework.hateoas.ResourceSupport` but is part of spring-boot (specifically, `spring-boot-actuator`) and is contained within a configuration class that is conditionally loaded based on the presence of `org.springframework.hateoas.Link`.  enunciate scans the classpath and picks it up which results in attempting to laod it which results in an exploding compiler.  

My next step is to dig into enunciate and determine how to exclude the type from 'Detected API Types' which I'll do later today and post back if I can get a work-around in place.

**Comment by Blackbaud-MikeLueders** [comment]
Okay, I was able to demonstrate this is the problem by excluding `spring-boot-starter-actuator` from the classpath and enunciate successfully finishes.  Next, I just updated the enunciate.xml as follows...
```
    <api-classes>
        <exclude pattern="org.springframework.*"/>
    </api-classes>
```
What I really want is to only include classes I care about but for some reason the gradle task is detecting no changes - I suspect this is a misconfiguration on my part.  

In any case, hopefully this helps someone else running into the same issue.

**Comment by tpokki** [comment]
I too had this issue after adding spring-boot-starter-actuator. Minor detail, but for the workaround I needed to have two stars in exclude pattern: 
```xml
    <api-classes>
        <exclude pattern="org.springframework.**"/>
    </api-classes>
```
