### ISSUE TITLE
Add possibiltiy to configure the validatorUrl for SwaggerUI

### ISSUE THREAD

**Issue by coder-hugo** [stoicflame/enunciate#815]
Most of our API documentations are only hosted internally so the `swagger.io` online validator will fail to retrieve the `swagger.json` which ends in an error shown in the UI. SwaggerUI provides the configuration parameter `validatorUrl` ([see](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network)) for such cases. With this you can either configure a different self-hosted validator that is able to retrieve the swagger.json or you can disable the validation at all by passing a value of `null` to this option. It would be nice if there would be an option in the swagger module for configuring the `validatorUrl`.

**Comment by stoicflame** [comment]
Finally got around to addressing this.

After taking some time to consider the request, I've decided I'm not going to provide this enhancement because it would require generating the index.html of the swagger base. This would be a heavy burden (because it changes so often), and violation of the principle of the separation of concerns.

So the solution to this, for now, is to provide a custom swagger base for your project.
