### ISSUE TITLE
How to remove json_ prefix from swagger.json

### ISSUE THREAD

**Issue by DiabolusExMachina** [stoicflame/enunciate#944]
Hi, 

is it possible to remove the "json_" Prefix from my types in the swagger.json? Currently every Class will be listet as for example json_Person. I looked at the Docs but I could not find a solution.

**Comment by stoicflame** [comment]
There's no way to customize that right now. It seems like a reasonable enhancement request, though.

**Comment by DiabolusExMachina** [comment]
Thank you for considering this!

**Comment by stoicflame** [comment]
Finally getting around to this. I can't reproduce the "ugly label" problem for my classes. So since the problem stated above is unclear, I can't provide a solution.

Here's what my swagger UI looks like in the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) (I don't see any `json_` prefixes in the class names:

![image](https://user-images.githubusercontent.com/145838/62827041-708ee180-bb84-11e9-9654-96102a17dddd.png)

**Comment by Schreigurke** [comment]
Hi there!

I think i can clarify DiabolusExMachina's problem since I've stumbled accross the same issue.
I am using the generated swagger.json file for generating a C# client via nswag and this is where  the issue becomes apparent. 
All classes and methods within the swagger.json have the "'json_' prefix and thus nswag generates 
it's classe with the same prefix.
So the problem is not within the UI itself but in the swagger.json file it is based on.

Sure, this problem can be fixed manually, but it still would be nice since it could be completely automated.

A little snipped from the swagger.json is attached to this post.

Best regards,
Frede

[swagger.zip](https://github.com/stoicflame/enunciate/files/3949516/swagger.zip)

**Comment by stoicflame** [comment]
I'll reopen and consider an enhancement to customize those ids.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)

**Comment by Schreigurke** [comment]
Thanks a lot for adding this enhancement!
