### ISSUE TITLE
Prevent @QueryParam alphabetical sorting order 

### ISSUE THREAD

**Issue by amakala** [stoicflame/enunciate#967]
Hello,

Is there a way to prevent enunciate from alphabeticaly sorting the `@QueryParam` parameters?
Best would be to keep the sequence define in the javadoc.

Best regards.

**Comment by stoicflame** [comment]
No, there's alternate sort order for the docs right now.

I'm happy to track this as an enhancement request, but it would need to be more defined. The sequence defined in the javadoc isn't good enough because query parameters can come from more than just method parameters. You'd have to define how to order query parameters defined by method parameters, fields, parent class fields, custom annotations, etc.

For now, I can't think of a better way to order query parameters, so I'll close this issue. I'm happy to reopen if you'd like to refine this into a more general enhancement request.
